# Reading and Cleaning Data

In [558]:
datafile = open("u.data", "r")
datafile1=open("u.item","r")

In [559]:
import pandas as pd
data = pd.read_csv("u.data", sep='\t', names=["UserID", "movie id", "Rating", "Timestamp"])

In [560]:
data.head()

UserID  movie id  Rating  Timestamp
0     196       242       3  881250949
1     186       302       3  891717742
2      22       377       1  878887116
3     244        51       2  880606923
4     166       346       1  886397596

In [561]:
data['Timestamp'] = pd.to_datetime(data['Timestamp'], unit='s')

In [562]:
data["Timestamp"]

0       1997-12-04 15:55:49
1       1998-04-04 19:22:22
2       1997-11-07 07:18:36
3       1997-11-27 05:02:03
4       1998-02-02 05:33:16
                ...        
99995   1997-11-22 05:10:44
99996   1997-11-17 19:39:03
99997   1997-09-20 22:49:55
99998   1997-12-17 22:52:36
99999   1997-11-19 17:13:03
Name: Timestamp, Length: 100000, dtype: datetime64[ns]

In [563]:
data.head()

UserID  movie id  Rating           Timestamp
0     196       242       3 1997-12-04 15:55:49
1     186       302       3 1998-04-04 19:22:22
2      22       377       1 1997-11-07 07:18:36
3     244        51       2 1997-11-27 05:02:03
4     166       346       1 1998-02-02 05:33:16

In [564]:
data=data.drop(["Timestamp"],axis=1)
data.head()

UserID  movie id  Rating
0     196       242       3
1     186       302       3
2      22       377       1
3     244        51       2
4     166       346       1

In [565]:
d = 'movie id | movie title | release date | video release date | IMDb URL | unknown | Action | Adventure | Animation | Children | Comedy | Crime | Documentary | Drama | Fantasy | Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi | Thriller | War | Western'
column_names2 = d.split(' | ')
column_names2

['movie id',
 'movie title',
 'release date',
 'video release date',
 'IMDb URL',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 'Children',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [566]:
movies_dataset = pd.read_csv('u.item', sep='|',header=None,names=column_names2,encoding='latin-1')
movies_dataset.head()

movie id        movie title release date  video release date  \
0         1   Toy Story (1995)  01-Jan-1995                 NaN   
1         2   GoldenEye (1995)  01-Jan-1995                 NaN   
2         3  Four Rooms (1995)  01-Jan-1995                 NaN   
3         4  Get Shorty (1995)  01-Jan-1995                 NaN   
4         5     Copycat (1995)  01-Jan-1995                 NaN   

                                            IMDb URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...        0       1   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)        0       0   

   Adventure  Animation  Children  ...  Fantasy  Film-Noir  Horror  Musical  \
0          0          1         1  ...        0          0       0        0   
1          1          0         0  ...        0          0       0        0   
2          0          0         0  ...        0          0       0        0   
3          0          0         0  ...        0          0       0        0   
4          0          0         0  ...        0          0       0        0   

   Mystery  Romance  Sci-Fi  Thriller  War  Western  
0        0        0       0         0    0        0  
1        0        0       0         1    0        0  
2        0        0       0         1    0        0  
3        0        0       0         0    0        0  
4        0        0       0         1    0        0  

[5 rows x 24 columns]

In [567]:
d = 'user_id | gender | zipcode | age_desc | occ_desc'
column_names3 = d.split(' | ')
column_names3

['user_id', 'gender', 'zipcode', 'age_desc', 'occ_desc']

In [568]:
user_dataset = pd.read_csv('u.user', sep='|',header=None,names=column_names3, encoding='latin-1')
user_dataset.head()

user_id  gender zipcode    age_desc occ_desc
0        1      24       M  technician    85711
1        2      53       F       other    94043
2        3      23       M      writer    32067
3        4      24       M  technician    43537
4        5      33       F       other    15213

## Data Pre-Processing

In [569]:

movie_genre = column_names2[-19:]

new_data = []

for _, row in movies_dataset.iterrows():
    movie_id = row['movie id']
    movie_title = row['movie title']
    genres = '|'.join([genre for genre in movie_genre if row[genre] == 1])
    new_data.append([movie_id, movie_title, genres])

new_df = pd.DataFrame(new_data, columns=['MovieID', 'movie_title', 'genre'])
print(new_df)


      MovieID                                movie_title  \
0           1                           Toy Story (1995)   
1           2                           GoldenEye (1995)   
2           3                          Four Rooms (1995)   
3           4                          Get Shorty (1995)   
4           5                             Copycat (1995)   
...       ...                                        ...   
1677     1678                          Mat' i syn (1997)   
1678     1679                           B. Monkey (1998)   
1679     1680                       Sliding Doors (1998)   
1680     1681                        You So Crazy (1994)   
1681     1682  Scream of Stone (Schrei aus Stein) (1991)   

                          genre  
0     Animation|Children|Comedy  
1     Action|Adventure|Thriller  
2                      Thriller  
3           Action|Comedy|Drama  
4          Crime|Drama|Thriller  
...                         ...  
1677                      Drama  
1678   

In [570]:
new_df

MovieID                                movie_title  \
0           1                           Toy Story (1995)   
1           2                           GoldenEye (1995)   
2           3                          Four Rooms (1995)   
3           4                          Get Shorty (1995)   
4           5                             Copycat (1995)   
...       ...                                        ...   
1677     1678                          Mat' i syn (1997)   
1678     1679                           B. Monkey (1998)   
1679     1680                       Sliding Doors (1998)   
1680     1681                        You So Crazy (1994)   
1681     1682  Scream of Stone (Schrei aus Stein) (1991)   

                          genre  
0     Animation|Children|Comedy  
1     Action|Adventure|Thriller  
2                      Thriller  
3           Action|Comedy|Drama  
4          Crime|Drama|Thriller  
...                         ...  
1677                      Drama  
1678           Romance|Thriller  
1679              Drama|Romance  
1680                     Comedy  
1681                      Drama  

[1682 rows x 3 columns]

# CONTENT BASED RECOMMENDATION

### Genre Based

In [571]:
# Break up the big genre string into a string array
new_df['genre'] = new_df['genre'].str.split('|')
# Convert genres to string value
new_df['genre'] = new_df['genre'].fillna("").astype('str')

In [572]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vector = TfidfVectorizer(analyzer='word',ngram_range=(1, 3),min_df=0, stop_words='english')
tfidf_matrix = tfidf_vector.fit_transform(new_df['genre'])
tfidf_matrix.shape

(1682, 252)

In [573]:
tfidf_matrix

<1682x252 sparse matrix of type '<class 'numpy.float64'>'
	with 4831 stored elements in Compressed Sparse Row format>

In [574]:
from sklearn.metrics.pairwise import linear_kernel
cos_similarity = linear_kernel(tfidf_matrix, tfidf_matrix)
cos_similarity[:4, :4]

array([[1.        , 0.        , 0.        , 0.04014005],
       [0.        , 1.        , 0.26955042, 0.07312989],
       [0.        , 0.26955042, 1.        , 0.        ],
       [0.04014005, 0.07312989, 0.        , 1.        ]])

In [575]:
# Built 1-dimensional arrays with movie titles and indices
titles = new_df['movie_title']
indices = pd.Series(new_df.index, index=new_df['movie_title'])

# Genre based recommendation on the basis of cosine similarity
def genre_recommendations(title):
    index = indices[title]
    score_similarity = list(enumerate(cos_similarity[index]))
    score_similarity = sorted(score_similarity, key=lambda x: x[1], reverse=True)
    score_similarity = score_similarity[1:11]
    movie_indices = [i[0] for i in score_similarity]
    return titles.iloc[movie_indices]

In [576]:
movie = str(input("Enter Movie name: "))
genre_recommendations(movie)

Enter Movie name: Star Wars (1977)


180                             Return of the Jedi (1983)
171                       Empire Strikes Back, The (1980)
473     Dr. Strangelove or: How I Learned to Stop Worr...
1238                              Cutthroat Island (1995)
270                              Starship Troopers (1997)
120                         Independence Day (ID4) (1996)
497                             African Queen, The (1951)
234                                  Mars Attacks! (1996)
876                                 Excess Baggage (1997)
946                 Big Blue, The (Grand bleu, Le) (1988)
Name: movie_title, dtype: object

### Popularity Based

In [577]:
merge_dataset=pd.merge(data,movies_dataset,on="movie id")
merge_dataset=merge_dataset[['movie id','movie title','UserID','Rating']]

In [578]:
merge_dataset.head()

movie id   movie title  UserID  Rating
0       242  Kolya (1996)     196       3
1       242  Kolya (1996)      63       3
2       242  Kolya (1996)     226       5
3       242  Kolya (1996)     154       3
4       242  Kolya (1996)     306       5

In [579]:
def popularity_recommendation():
    popular_movies = merge_dataset.groupby(['movie title']).agg({"Rating":"count"})['Rating'].sort_values(ascending=False)
    popular_movies = popular_movies.to_frame()
    popular_movies.reset_index(level=0, inplace=True)
    popular_movies.columns = ['movie title', 'Number of Users watched']
    return popular_movies

In [580]:
popularity_recommendation()

movie title  Number of Users watched
0                       Star Wars (1977)                      583
1                         Contact (1997)                      509
2                           Fargo (1996)                      508
3              Return of the Jedi (1983)                      507
4                       Liar Liar (1997)                      485
...                                  ...                      ...
1659       Great Day in Harlem, A (1994)                        1
1660    Other Voices, Other Rooms (1997)                        1
1661                 Good Morning (1971)                        1
1662                   Girls Town (1996)                        1
1663  Á köldum klaka (Cold Fever) (1994)                        1

[1664 rows x 2 columns]

In [581]:
popularity_recommendation()[popularity_recommendation()['Number of Users watched'] >= 400]

movie title  Number of Users watched
0                 Star Wars (1977)                      583
1                   Contact (1997)                      509
2                     Fargo (1996)                      508
3        Return of the Jedi (1983)                      507
4                 Liar Liar (1997)                      485
5      English Patient, The (1996)                      481
6                    Scream (1996)                      478
7                 Toy Story (1995)                      452
8             Air Force One (1997)                      431
9    Independence Day (ID4) (1996)                      429
10  Raiders of the Lost Ark (1981)                      420
11           Godfather, The (1972)                      413

### Average-Rating Based 

In [582]:
def avg_rating_recommendations():
    avg_rated_movies = merge_dataset.groupby('movie title')['Rating'].mean().sort_values(ascending=False)
    avg_rated_movies = avg_rated_movies.to_frame()
    avg_rated_movies.reset_index(level=0, inplace=True)
    avg_rated_movies.columns = ['movie title', 'avg rating']
    
    return avg_rated_movies

In [583]:
avg_rating_recommendations()

movie title  avg rating
0                   They Made Me a Criminal (1939)         5.0
1       Marlene Dietrich: Shadow and Light (1996)          5.0
2             Saint of Fort Washington, The (1993)         5.0
3                    Someone Else's America (1995)         5.0
4                                  Star Kid (1997)         5.0
...                                            ...         ...
1659  Eye of Vichy, The (Oeil de Vichy, L') (1993)         1.0
1660                       King of New York (1990)         1.0
1661     Touki Bouki (Journey of the Hyena) (1973)         1.0
1662                      Bloody Child, The (1996)         1.0
1663                       Crude Oasis, The (1995)         1.0

[1664 rows x 2 columns]

In [584]:
avg_rating_recommendations()[avg_rating_recommendations()['avg rating'] >= 4.0]

movie title  avg rating
0                       They Made Me a Criminal (1939)         5.0
1           Marlene Dietrich: Shadow and Light (1996)          5.0
2                 Saint of Fort Washington, The (1993)         5.0
3                        Someone Else's America (1995)         5.0
4                                      Star Kid (1997)         5.0
..                                                 ...         ...
168  I Don't Want to Talk About It (De eso no se ha...         4.0
169                                      Priest (1994)         4.0
170                                   Duck Soup (1933)         4.0
171                           Wedding Gift, The (1994)         4.0
172                 Killer: A Journal of Murder (1995)         4.0

[173 rows x 2 columns]

In [585]:
print("Number of movies with Rating equal to 5 are : "+ str(sum(avg_rating_recommendations()['avg rating'] == 5.0)))
print("Number of movies with Rating greater than 4 and less than 5 are : "+ str(sum(avg_rating_recommendations()['avg rating'] >= 4.0)-sum(avg_rating_recommendations()['avg rating'] == 5.0)))
print("Number of movies with Rating greater than 3 and less than 4 are : "+ str(sum(avg_rating_recommendations()['avg rating'] >= 3.0)-sum(avg_rating_recommendations()['avg rating'] >= 4.0)))
print("Number of movies with Rating greater than 2 and less than 3 are : "+ str(sum(avg_rating_recommendations()['avg rating'] >= 2.0)-sum(avg_rating_recommendations()['avg rating'] >= 3.0)))
print("Number of movies with Rating greater than 1 and less than 2 are : "+ str(sum(avg_rating_recommendations()['avg rating'] >= 1.0)-sum(avg_rating_recommendations()['avg rating'] >= 2.0)))

Number of movies with Rating equal to 5 are : 10
Number of movies with Rating greater than 4 and less than 5 are : 163
Number of movies with Rating greater than 3 and less than 4 are : 871
Number of movies with Rating greater than 2 and less than 3 are : 492
Number of movies with Rating greater than 1 and less than 2 are : 128


# Profile Based or Collaborative Filtering recommendation system

### Training Model for Item-based & User-based Collaborative recommendation system

In [586]:
small_data = data.sample(frac=0.05)

In [587]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(small_data, test_size=0.2)
train_data

UserID  movie id  Rating
73007      62       217       2
99386     868       211       3
35554     622       845       3
38337     481       427       4
53507     534       405       3
...       ...       ...     ...
26653     263        87       4
63552     291       173       5
36562     605       180       4
75056     825       593       3
89502     747       192       5

[4000 rows x 3 columns]

In [588]:
# Created 2 matrices for train_data and test_data
train_data_matrix = train_data[['UserID', 'movie id', 'Rating']].values
test_data_matrix = test_data[['UserID', 'movie id', 'Rating']].values


print(train_data_matrix.shape)
print(test_data_matrix.shape)
train_data_matrix

(4000, 3)
(1000, 3)


array([[ 62, 217,   2],
       [868, 211,   3],
       [622, 845,   3],
       ...,
       [605, 180,   4],
       [825, 593,   3],
       [747, 192,   5]], dtype=int64)

In [589]:
from sklearn.metrics.pairwise import pairwise_distances
import numpy as np

# calculated user similarity matrix by using pairwise_distances
user_matrix = 1 - pairwise_distances(train_data, metric='correlation')
user_matrix[np.isnan(user_matrix)] = 0
print(user_matrix[:5, :5])
user_matrix.shape

[[ 1.         -0.01735167  0.8703318   0.63951374  0.5331876 ]
 [-0.01735167  1.          0.47728994  0.75756729  0.83661797]
 [ 0.8703318   0.47728994  1.          0.93518684  0.88067473]
 [ 0.63951374  0.75756729  0.93518684  1.          0.99136611]
 [ 0.5331876   0.83661797  0.88067473  0.99136611  1.        ]]


(4000, 4000)

In [590]:
# calculated items similarity matrix by using pairwise_distances
item_matrix = 1 - pairwise_distances(train_data_matrix.T, metric='correlation')
item_matrix[np.isnan(item_matrix)] = 0
print(item_matrix[:5, :5])
item_matrix.shape

[[ 1.          0.02099603 -0.02070099]
 [ 0.02099603  1.         -0.19171211]
 [-0.02070099 -0.19171211  1.        ]]


(3, 3)

In [591]:
# predicting ratings so that we can compare between the ouptut of this model and given ratings(test_data)
def predict_rating(dataset, similarity, type='user'):
    if type == 'user':
        mean_user_rating = dataset.mean(axis=1)
        ratings_diff = (dataset - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = dataset.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
        
    return pred

In [592]:
from sklearn.metrics import mean_squared_error
from math import sqrt

# calculated rmse error between rating of datasets and predicted rating for given model
def rmse(pred, actual_ratings):
    pred = pred[actual_ratings.nonzero()].flatten()
    actual_ratings = actual_ratings[actual_ratings.nonzero()].flatten()
    return sqrt(mean_squared_error(pred, actual_ratings))

In [593]:
# Predicted ratings on the training data with both similarity score
user_prediction = predict_rating(train_data_matrix, user_matrix, type='user')
item_prediction = predict_rating(train_data_matrix, item_matrix, type='item')

# RMSE on the test data
print('User-based RMSE: ' + str(rmse(user_prediction, test_data_matrix)))
print('Item-based RMSE: ' + str(rmse(item_prediction, test_data_matrix)))

User-based RMSE: 308.4716407252331
Item-based RMSE: 347.3650782145119


In [594]:
# RMSE on the train data
print('User-based RMSE: ' + str(rmse(user_prediction, train_data_matrix)))
print('Item-based RMSE: ' + str(rmse(item_prediction, train_data_matrix)))

User-based RMSE: 140.82374001094013
Item-based RMSE: 74.6791526928428


As we can see there is very huge error by using simple training model , so now we use KNN model

### Training KNN Model for Item-Based Collaborative recommendation system

In [595]:
merge_dataset=pd.merge(data,items_dataset,on="movie id")
merge_dataset=merge_dataset[['movie id','movie title','UserID','Rating']]
merge_dataset.shape

(100000, 4)

In [596]:
merge_dataset.head()

movie id   movie title  UserID  Rating
0       242  Kolya (1996)     196       3
1       242  Kolya (1996)      63       3
2       242  Kolya (1996)     226       5
3       242  Kolya (1996)     154       3
4       242  Kolya (1996)     306       5

In [597]:
refined_dataset = merge_dataset.groupby(by=['UserID','movie title'], as_index=False).agg({"Rating":"mean"})

refined_dataset

UserID                          movie title  Rating
0           1                101 Dalmatians (1996)     2.0
1           1                  12 Angry Men (1957)     5.0
2           1  20,000 Leagues Under the Sea (1954)     3.0
3           1         2001: A Space Odyssey (1968)     4.0
4           1                    Abyss, The (1989)     3.0
...       ...                                  ...     ...
99688     943             Wizard of Oz, The (1939)     3.0
99689     943                          Wolf (1994)     2.0
99690     943                    Wyatt Earp (1994)     1.0
99691     943                    Young Guns (1988)     4.0
99692     943                 Young Guns II (1990)     3.0

[99693 rows x 3 columns]

In [598]:
refined_dataset.shape

(99693, 3)

In [599]:
# created movie-user dataframe
movie_user = refined_dataset.pivot(
    index='UserID',
     columns='movie title',
      values='Rating').fillna(0)

movie_user.head()

movie title  'Til There Was You (1997)  1-900 (1994)  101 Dalmatians (1996)  \
UserID                                                                        
1                                  0.0           0.0                    2.0   
2                                  0.0           0.0                    0.0   
3                                  0.0           0.0                    0.0   
4                                  0.0           0.0                    0.0   
5                                  0.0           0.0                    2.0   

movie title  12 Angry Men (1957)  187 (1997)  2 Days in the Valley (1996)  \
UserID                                                                      
1                            5.0         0.0                          0.0   
2                            0.0         0.0                          0.0   
3                            0.0         2.0                          0.0   
4                            0.0         0.0                          0.0   
5                            0.0         0.0                          0.0   

movie title  20,000 Leagues Under the Sea (1954)  \
UserID                                             
1                                            3.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
5                                            0.0   

movie title  2001: A Space Odyssey (1968)  \
UserID                                      
1                                     4.0   
2                                     0.0   
3                                     0.0   
4                                     0.0   
5                                     4.0   

movie title  3 Ninjas: High Noon At Mega Mountain (1998)  \
UserID                                                     
1                                                    0.0   
2                                                    1.0   
3                                                    0.0   
4                                                    0.0   
5                                                    0.0   

movie title  39 Steps, The (1935)  ...  Yankee Zulu (1994)  \
UserID                             ...                       
1                             0.0  ...                 0.0   
2                             0.0  ...                 0.0   
3                             0.0  ...                 0.0   
4                             0.0  ...                 0.0   
5                             0.0  ...                 0.0   

movie title  Year of the Horse (1997)  You So Crazy (1994)  \
UserID                                                       
1                                 0.0                  0.0   
2                                 0.0                  0.0   
3                                 0.0                  0.0   
4                                 0.0                  0.0   
5                                 0.0                  0.0   

movie title  Young Frankenstein (1974)  Young Guns (1988)  \
UserID                                                      
1                                  5.0                3.0   
2                                  0.0                0.0   
3                                  0.0                0.0   
4                                  0.0                0.0   
5                                  4.0                0.0   

movie title  Young Guns II (1990)  Young Poisoner's Handbook, The (1995)  \
UserID                                                                     
1                             0.0                                    0.0   
2                             0.0                                    0.0   
3                             0.0                                    0.0   
4                             0.0                                    0.0   
5                             0.0                 

In [600]:
movie_user.shape

(943, 1664)

In [601]:
pip install scipy

In [602]:
# transformed matrix to scipy sparse matrix for save memory 
from scipy.sparse import csr_matrix
movie_user_sparse = csr_matrix(movie_user.values)
movie_user_sparse

<943x1664 sparse matrix of type '<class 'numpy.float64'>'
	with 99693 stored elements in Compressed Sparse Row format>

#### Fitting K-Nearest Neighbours model to the sparse matrix: 

In [603]:
from sklearn.neighbors import NearestNeighbors
knn_model = NearestNeighbors(metric='cosine', algorithm='brute')
knn_model.fit(movie_user_sparse)

NearestNeighbors(algorithm='brute', metric='cosine')

In [604]:
# first get similar users
def similar_users(user, n): #takes user and number of similar users we want

  input_user = np.asarray([movie_user.values[user-1]])  
  distances, indices = knn_model.kneighbors(input_user, n_neighbors=n+1)
  
  print("Users similar to the input User-",user, "are: ")
  print(" ")
  for i in range(1,len(distances[0])):
    if distances[0][i]<=0.6: #setting threshold for better results only
       print(i,". User:", indices[0][i]+1, "separated by distance of",distances[0][i])
  return indices.flatten()[1:] + 1, distances.flatten()[1:]

#### Getting similar users and calculating distance among neighbours of input user

In [605]:
from pprint import pprint
user_id = int(input("Enter user ID: "))
print(" Few of movies seen by the User:")
pprint(list(refined_dataset[refined_dataset['UserID'] == user_id]['movie title'])[:10])
similar_user_list, distance_list = get_similar_users(user_id,10)

Enter user ID: 585
 Few of movies seen by the User:
['8 1/2 (1963)',
 'Angels and Insects (1995)',
 "Antonia's Line (1995)",
 'Aparajito (1956)',
 'Ballad of Narayama, The (Narayama Bushiko) (1958)',
 'Before the Rain (Pred dozhdot) (1994)',
 'Belle de jour (1967)',
 'Bhaji on the Beach (1993)',
 'Boogie Nights (1997)',
 'Bread and Chocolate (Pane e cioccolata) (1973)']
Top users who are very much similar to the User- 585 are: 
 
1 . User: 565 separated by distance of 0.47041692399507773
2 . User: 855 separated by distance of 0.5736853554704022
3 . User: 861 separated by distance of 0.5934084862288491
4 . User: 828 separated by distance of 0.5976339445637332


In [606]:
similar_user_list, distance_list

(array([565, 855, 861, 828, 884, 894, 639, 829, 909, 354], dtype=int64),
 array([0.47041692, 0.57368536, 0.59340849, 0.59763394, 0.60676497,
        0.6202157 , 0.63494282, 0.64994196, 0.67000252, 0.69733682]))

In [607]:
weightage_list = distance_list/np.sum(distance_list)
weightage_list

array([0.07693654, 0.09382607, 0.09705178, 0.09774285, 0.09923623,
       0.10143609, 0.1038447 , 0.10629781, 0.10957871, 0.11404923])

In [608]:
mov_rtngs_sim_users = movie_user.values[similar_user_list]
mov_rtngs_sim_users

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 3., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [609]:
movies_list = movie_user.columns
movies_list

Index([''Til There Was You (1997)', '1-900 (1994)', '101 Dalmatians (1996)',
       '12 Angry Men (1957)', '187 (1997)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '3 Ninjas: High Noon At Mega Mountain (1998)', '39 Steps, The (1935)',
       ...
       'Yankee Zulu (1994)', 'Year of the Horse (1997)', 'You So Crazy (1994)',
       'Young Frankenstein (1974)', 'Young Guns (1988)',
       'Young Guns II (1990)', 'Young Poisoner's Handbook, The (1995)',
       'Zeus and Roxanne (1997)', 'unknown',
       'Á köldum klaka (Cold Fever) (1994)'],
      dtype='object', name='movie title', length=1664)

#### Converting Weightage_list for being compatible with similar_user list for matrix operations

In [610]:
weightage_list = weightage_list[:,np.newaxis] + np.zeros(len(movies_list))
weightage_list

array([[0.07693654, 0.07693654, 0.07693654, ..., 0.07693654, 0.07693654,
        0.07693654],
       [0.09382607, 0.09382607, 0.09382607, ..., 0.09382607, 0.09382607,
        0.09382607],
       [0.09705178, 0.09705178, 0.09705178, ..., 0.09705178, 0.09705178,
        0.09705178],
       ...,
       [0.10629781, 0.10629781, 0.10629781, ..., 0.10629781, 0.10629781,
        0.10629781],
       [0.10957871, 0.10957871, 0.10957871, ..., 0.10957871, 0.10957871,
        0.10957871],
       [0.11404923, 0.11404923, 0.11404923, ..., 0.11404923, 0.11404923,
        0.11404923]])

In [611]:
new_rating_matrix = weightage_list*mov_rtngs_sim_users
mean_rating_list = new_rating_matrix.sum(axis =0)
mean_rating_list

array([0.        , 0.        , 0.61660211, ..., 0.        , 0.        ,
       0.        ])

In [612]:
from pprint import pprint
#this fuunction will recommend movie based on similar user
def recommend_movies(n):
  n = min(len(mean_rating_list),n)
  pprint(list(movies_list[np.argsort(mean_rating_list)[::-1][:n]]))

In [613]:
print("Movies recommended based on similar users are: ")
recommend_movies(5)

Movies recommended based on similar users are: 
['Fargo (1996)',
 'Indiana Jones and the Last Crusade (1989)',
 'Raiders of the Lost Ark (1981)',
 'Star Wars (1977)',
 'Willy Wonka and the Chocolate Factory (1971)']


#### This function filters the recommendation and  removes the movies which are already seen by the current user or not at all seen by any of the similar users.

In [614]:
def filtered_recommendations(n):
  
  zero_index = np.where(mean_rating_list == 0)[0][-1] #searching indices with zero rating
  sorted_index = np.argsort(mean_rating_list)[::-1]
  sorted_index = sorted_index[:list(sorted_index).index(zero_index)]
  n = min(len(sorted_index),n)
  movies_watched = list(refined_dataset[refined_dataset['UserID'] == user_id]['movie title'])
  movie_list = list(movies_list[sorted_index])
  count = 0
  final_movie_list = []
  for i in movie_list:
    if i not in movies_watched:
      count+=1
      final_movie_list.append(i)
    if count == n:
      break
  if count == 0:
    print("Good Recommendation: ")
  else:
    pprint(final_movie_list)

In [615]:
filtered_recommendations(5)

['Fargo (1996)',
 'Indiana Jones and the Last Crusade (1989)',
 'Raiders of the Lost Ark (1981)',
 'Star Wars (1977)',
 'Willy Wonka and the Chocolate Factory (1971)']


# Hybrid Recommendation System by using different Content-Based System

In [616]:
def hybrid_recommendations(title, genre_weight, popularity_weight, avg_rating_weight, top_n=10):
    # converting genre_recommendations to list
    genre_recs = list(genre_recommendations(title))

    # Converting popularity-based recommendations to list
    popularity_recs = popularity_recommendation()[popularity_recommendation()['Number of Users watched'] >= 400]['movie title'].tolist()

    # Converting average-rating based recommendations to list
    avg_rating_recs = avg_rating_recommendations()[avg_rating_recommendations()['avg rating'] >= 4.0]['movie title'].tolist()

    # Combining recommendations using weighted averages
    combined_recs = {}
    for movie_title in genre_recs:
        combined_recs[movie_title] = (
            genre_weight * genre_recs.index(movie_title) +
            popularity_weight * popularity_recs.count(movie_title) +
            avg_rating_weight * avg_rating_recs.count(movie_title)
        )

    # Sort the combined recommendations by the weighted sum
    sorted_recs = sorted(combined_recs.items(), key=lambda x: x[1], reverse=True)
    sorted_recs = [x[0] for x in sorted_recs]

    # Return the top N recommendations
    return sorted_recs[:top_n]


In [617]:
movie=str(input("Enter movie for recommendation: "))
recommended_movies = hybrid_recommendations(movie, genre_weight=0.01, popularity_weight=0.9, avg_rating_weight=0.09, top_n=10)
print("Hybrid Recommendations: ")
print(recommended_movies)

Enter movie for recommendation: Star Wars (1977)
Hybrid Recommendations: 
['Return of the Jedi (1983)', 'Independence Day (ID4) (1996)', 'African Queen, The (1951)', 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)', 'Empire Strikes Back, The (1980)', 'Big Blue, The (Grand bleu, Le) (1988)', 'Excess Baggage (1997)', 'Mars Attacks! (1996)', 'Starship Troopers (1997)', 'Cutthroat Island (1995)']
